services:
  app:
    container_name: actualutils
    build: .
    env_file:
      - .env
    volumes:
      - './data/config/:/app/config/'
    restart: unless-stopped
  filebrowser:
    image: filebrowser/filebrowser
    user: "${UID}:${GID}"
    ports:
      - 5010:80
    volumes:
      - './data/config/:/srv'
      - './data/filebrowser_cfg/:/config'
      - './data/filebrowser_db/:/database'
    environment:
      - FB_NOAUTH=noauth
    restart: unless-stopped
    entrypoint: [ "/filebrowser", "-d", "/database/filebrowser.db" ]