# NOTE: Will always try to match whole words (wraps a leading & trailing \b around the regex automatically).
#       If you want to match not whole words, you can use .+? at the beginning and/or end of the regex.

# The group currently does nothing (except provide a way to group multiple regexes under a single name).
# To automatically set a category for a category, use a key named "category" with the value of the category name.

External Files:
  # Optional file to load within the payee_aggregates folder under this group
  file: example.yaml
  # Optional category to set for all transactions in the file under the payees
  category: Extra stuff
  # Add a list of payees, K: V pairs, where K is the payee and V is a regex or a list of regexes
  Payee: regex
  Payee2:
    - regex1.*
    - regex2 \d{2}

Reise:
  Taxfree:
    - Duty ?free
    - Tax ?free

Parkering:
  category: Parkering
  Easypark: easypark
  Autopay: autopay

Spill:
  Steam: steam
  HumbleBundle: humblebundl.*

Elektronikk:
  Elkjøp: elkjoe?p
  Elektroimportøren: elektroimportoeren
  Kjell & Co:
    - kjell ?& ?co
    - kjell ?& ?company
  Komplett: komplett\.no
  Proshop: proshop

Byggevarehus:
  Biltema: biltema
  Coop Obs Bygg: coop obs bygg
  IKEA: ikea
  Jula: jula

Matbutikker:
  category: Mat
  Coop Obs: (coop )?obs ?(?!bygg)
  Coop Extra: extra
  Kiwi: kiwi
  Helgø Meny: helgoe meny
  Rema 1000: rema

Elbillading:
  category: Elbillading
  Circle K Lading: ev-\d+.*circle ?k?

Bensinstasjoner:
  Circle K: ^(?!ev-\d+).*circle ?k